spring:
  # h2
  #  datasource:
  #    url: jdbc:h2:mem:ju_market_system_db
  #    username: diego
  #    password:
  datasource:
    url: jdbc:mysql://mysqldb:3306/jumarketdb
    username: sa
    password: jumarketmaster1234
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    properties:
      hibernate.format_sql: true
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        trace: false
#        web-allow-others: false

server:
  servlet:
    contextPath: /api
springdoc:
  swagger-ui:
    path: /swagger-ui.html