CREATE TABLE coupon
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code            VARCHAR(255)                            NOT NULL,
    discount_type   INT                                     NOT NULL,
    discount_value  DECIMAL(19, 2)                          NOT NULL,
    expiration_date date                                    NOT NULL,
    CONSTRAINT pk_coupon PRIMARY KEY (id)
);

CREATE TABLE category
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id)
);

CREATE TABLE product
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255)                            NOT NULL,
    measuring_unit INT                                     NOT NULL,
    price          DECIMAL(19, 2)                          NOT NULL,
    quantity       DECIMAL(19, 2)                          NOT NULL,
    category_id    BIGINT,
    CONSTRAINT pk_product PRIMARY KEY (id)
);
CREATE TABLE cart
(
    id                        UUID NOT NULL,
    total_price               DECIMAL(19, 2),
    coupon_id                 BIGINT,
    payment_type              INT,
    total_price_with_discount DECIMAL(19, 2),
    date                      date,
    CONSTRAINT pk_cart PRIMARY KEY (id)
);

CREATE TABLE cart_product
(
    quantity   DECIMAL(19, 2) NOT NULL,
    cart_id    UUID           NOT NULL,
    product_id BIGINT         NOT NULL,
    CONSTRAINT pk_cart_product PRIMARY KEY (cart_id, product_id)
);

ALTER TABLE cart_product
    ADD CONSTRAINT FK_CART_PRODUCT_ON_CARTID FOREIGN KEY (cart_id) REFERENCES cart (id);

ALTER TABLE cart_product
    ADD CONSTRAINT FK_CART_PRODUCT_ON_PRODUCTID FOREIGN KEY (product_id) REFERENCES product (id);

ALTER TABLE category
    ADD CONSTRAINT uc_category_name UNIQUE (name);

ALTER TABLE product
    ADD CONSTRAINT FK_PRODUCT_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES category (id);

ALTER TABLE cart
    ADD CONSTRAINT FK_CART_ON_COUPON FOREIGN KEY (coupon_id) REFERENCES coupon (id);

