CREATE TABLE category
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id)
);

CREATE TABLE coupon
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    discount_type   INT                                     NOT NULL,
    discount_value  DECIMAL                                 NOT NULL,
    expiration_date date                                    NOT NULL,
    CONSTRAINT pk_coupon PRIMARY KEY (id)
);

CREATE TABLE sale
(
    id                        UUID    NOT NULL,
    total_price               DECIMAL NOT NULL,
    coupon_id                 BIGINT,
    payment_type              INT     NOT NULL,
    total_price_with_discount DECIMAL,
    date                      date    NOT NULL,
    cart_id                   UUID,
    CONSTRAINT pk_sale PRIMARY KEY (id)
);


CREATE TABLE cart
(
    id      UUID NOT NULL,
    sale_id UUID,
    CONSTRAINT pk_cart PRIMARY KEY (id)
);

CREATE TABLE product
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255)                            NOT NULL,
    measuring_unit VARCHAR(2)                              NOT NULL,
    price          DECIMAL                                 NOT NULL,
    quantity       DECIMAL                                 NOT NULL,
    category_id    BIGINT,
    CONSTRAINT pk_product PRIMARY KEY (id)
);

CREATE TABLE cart_sale
(
    cart_id    UUID   NOT NULL,
    product_id BIGINT NOT NULL,
    quantity   INT    NOT NULL,
    CONSTRAINT pk_cart_sale PRIMARY KEY (cart_id, product_id)
);

ALTER TABLE cart
    ADD CONSTRAINT FK_CART_ON_SALE FOREIGN KEY (sale_id) REFERENCES sale (id);

ALTER TABLE sale
    ADD CONSTRAINT FK_SALE_ON_CART FOREIGN KEY (cart_id) REFERENCES cart (id);

ALTER TABLE sale
    ADD CONSTRAINT FK_SALE_ON_COUPON FOREIGN KEY (coupon_id) REFERENCES coupon (id);

ALTER TABLE product
    ADD CONSTRAINT FK_PRODUCT_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES category (id);

ALTER TABLE cart_sale
    ADD CONSTRAINT FK_CART_SALE_ON_CART FOREIGN KEY (cart_id) REFERENCES cart (id);

ALTER TABLE cart_sale
    ADD CONSTRAINT FK_CART_SALE_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id);